version: '3.8'

# Development override for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DEBUG=true
      - NODE_ENV=development
    command: python run.py --reload

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
  - REACT_APP_API_BASE_URL=http://localhost:5000
  - REACT_APP_AEM_BUILDER_URL=http://localhost:8080
    command: npm start

  aem-mcp-server:
    volumes:
      - ./aem-mcp-server/src:/app/src
    environment:
      - NODE_ENV=development
      - DEBUG=true
    command: npm run dev
